version: '3'
services:
  web:
    image: 'tomcat:9.0.38'
    volumes:
      - ./target/Lobici.war:/usr/local/tomcat/webapps/Lobici.war
    ports:
      - '8082:8080'

  db:
    image: 'mysql:8.0.21'
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "Lobici"
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysqldata: {}

        
